/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-07-08 05:16:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("	<html>\n");
      out.write("	<head>\n");
      out.write("		<meta charset=\"utf-8\">\n");
      out.write("		<title>산책어때</title>\n");
      out.write("		<link href=\"index.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("		<script src=\"jquery.min.js\"></script>\n");
      out.write("		<script src=\"script.js\"></script>\n");
      out.write("	</head>\n");
      out.write("	<body>\n");
      out.write("    <div id=\"wrap\">\n");
      out.write("        <header id=\"header\">\n");
      out.write("            <h1 class=\"logo\">\n");
      out.write("                <a href=\"#\">산책어때</a>\n");
      out.write("            </h1>\n");
      out.write("            <a href=\"login.jsp\">Login</a>\n");
      out.write("            <nav class=\"nav\">\n");
      out.write("                <ul>\n");
      out.write("                    <li><a href=\"#\">산책어때</a>\n");
      out.write("                        <ul class=\"submenu\">\n");
      out.write("                            <li><a href=\"introduce.jsp\">산책어때 소개</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>    \n");
      out.write("                    <li><a href=\"#\">예약하기</a>\n");
      out.write("                        <ul class=\"submenu\">\n");
      out.write("                            <li><a href=\"#\">산책하고싶은 강아지</a></li>	\n");
      out.write("                            <li><a href=\"#\">산책을 시키고 싶은 지원자</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>    					\n");
      out.write("                    <li><a href=\"#\">커뮤니티</a>\n");
      out.write("                        <ul class=\"submenu\">		\n");
      out.write("                            <li><a href=\"#\">리뷰</a></li>	\n");
      out.write("                            <li><a href=\"board.jsp\">자유게시판</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                     </li>  \n");
      out.write("                    <li><a href=\"#\">로그인</a>\n");
      out.write("                        <ul class=\"submenu\">\n");
      out.write("                        	<li><a href=\"login.jsp\">로그인</a></li>	\n");
      out.write("                            <li><a href=\"register.jsp\">회원가입</a></li>		\n");
      out.write("                            <li><a href=\"mypage.jsp\">마이페이지</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>    		\n");
      out.write("                </ul>\n");
      out.write("            </nav>\n");
      out.write("        </header>\n");
      out.write("        <!-- header 끝 -->\n");
      out.write("		<div id=\"slide\">\n");
      out.write("			<div class=\"slide_list\">\n");
      out.write("				<ul>\n");
      out.write("					<li class=\"s1\"><a href=\"#\"></a></li>\n");
      out.write("					<li class=\"s2\"><a href=\"#\"></a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("        <div id=\"contents\">\n");
      out.write("			<div class=\"content1\">본문1</div>\n");
      out.write("			<div class=\"content2\">본문2</div>\n");
      out.write("            <div class=\"content3\">본문3</div>\n");
      out.write("        </div>\n");
      out.write("        <footer id=\"footer\">\n");
      out.write("            <div class=\"footer1\">\n");
      out.write("                <h4>산책어때</h4>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"footer2\">\n");
      out.write("                <div class=\"footer2-1\">\n");
      out.write("                    <ul>\n");
      out.write("                        <li><a href=\"#\">개인정보처리방침</a></li>\n");
      out.write("                        <li><a href=\"#\">회사소개</a></li>\n");
      out.write("                        <li><a href=\"#\">이메일무단수집거부</a></li>\n");
      out.write("                        <li><a href=\"#\">고객센터</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"footer2-2\">\n");
      out.write("                    COPYRIGHT 2024, All Rights Reseved\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("    </div>\n");
      out.write("    <!-- currentPage : 현재 보고있는 페이지번호 -->\n");
      out.write("		<!-- recordsPerPage : 한페이지 당 보여줄 게시글 수 -->\n");
      out.write("		<!-- limit n1, n2 -->\n");
      out.write("		<!-- 다음번에 시작되는 자료의 번호는 n1+n2+1 -->\n");
      out.write("		<!-- P1 : 1~10  (n1=0, n2=10)-->\n");
      out.write("		<!-- P2 : 11~20 (n1=10, n2=10)-->\n");
      out.write("		<!-- P3 : 21~30 (n1=20, n2=10)-->\n");
      out.write("		<form action=\"ReadPage\" method=\"get\">\n");
      out.write("			<input type=\"hidden\" name=\"currentPage\" value=\"1\">\n");
      out.write("			한 페이지에 보여줄 게시글 수를 골라주세요\n");
      out.write("			<select name=\"recordsPerPage\">\n");
      out.write("				<option value=\"5\">5개씩보기</option>\n");
      out.write("				<option value=\"10\" selected>10개씩보기</option>\n");
      out.write("				<option value=\"15\">15개씩보기</option>\n");
      out.write("			</select>\n");
      out.write("			<input type=\"submit\" value=\"보기\">\n");
      out.write("		</form>\n");
      out.write("	</body>\n");
      out.write("	\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
